<?php

/**
 * Classes for tracking shipments.
 * 
 * PHP versions 5.
 * 
 * @category  Services
 * @package   Services_Shipping
 * @author    Kristopher Ives <nullmind@gmail.com>
 * @copyright 2008 Santiance Corporation
 * @license   LGPL http://www.gnu.org/licenses/lgpl-3.0.txt
 * @version   CVS: $Id:$
 * @link      http://www.santiance.com/open/Services_Shipping
 */

require_once 'Services/Shipping/ShipmentEstimate.php';
require_once 'Services/Shipping/ShipmentLabel.php';

/**
 * Describes a transaction with a Carrier regarding a
 * Shipment.
 * 
 * @category Services
 * @package  Services_Shipping
 * @author   Kristopher Ives <nullmind@gmail.com>
 * @license  LGPL http://www.gnu.org/licenses/lgpl-3.0.txt
 * @link     http://www.santiance.com/open/Services_Shipping/Carrier
 */
interface Services_Shipping_ShipmentReceipt
{
    /**
     * Gets the label generated by the shipment.
     * 
     * @return Services_Shipping_ShipmentLabel|null the generated label; or
     *         null of no label was generated
     */
    public function getLabel();
    
    /**
     * Gets the tracking identifier for the shipment. It should be in the
     * same format as {@link Services_Shipping_Carrier#track()}
     * 
     * @return string the tracking identifier
     */
    public function getTrackingId();
    
    /**
     * Gets an estimate of the shipment this receipt is for.
     * 
     * @return Services_Shipping_ShipmentEstimate the shipment estimate
     */
    public function getEstimate();
}
?>